name: PING Devices
favicon: null
layout_spectrum: 0.29303747112862766
typography_spectrum: 0.628568610176444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#85888d'
    - '#3d3d3d'
    - '#db361d'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
