name: PING Devices
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'PING Devices '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#62737d'
    - '#2d3538'
    - '#f9fdfe'
    - '#9ea5ad'
    - '#bdc2c5'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
