name: PING Devices
favicon: null
layout_spectrum: 0.29303747112862766
typography_spectrum: 0.628568610176444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#94a0ac'
    - '#4f5f76'
    - '#010000'
    - '#323019'
  brandStrength: 0.6726591486949474
  lightness: 0.5671425075270236
  saturation: 0.5125005978625268
  rhythmicContrast: 0.014868825674057007
purpose: []
